package practical.wjc.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import practical.wjc.entity.Goods;

public class GoodsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_goods
     *
     * @mbggenerated
     */
    public String insertSelective(Goods record) {
        BEGIN();
        INSERT_INTO("ps_goods");
        
        if (record.getGoodsid() != null) {
            VALUES("goodsid", "#{goodsid,jdbcType=INTEGER}");
        }
        
        if (record.getTypeid() != null) {
            VALUES("typeid", "#{typeid,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsname() != null) {
            VALUES("goodsname", "#{goodsname,jdbcType=VARCHAR}");
        }
        
        if (record.getSize() != null) {
            VALUES("size", "#{size,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsprice() != null) {
            VALUES("goodsprice", "#{goodsprice,jdbcType=VARCHAR}");
        }
        
        if (record.getImages() != null) {
            VALUES("images", "#{images,jdbcType=VARCHAR}");
        }
        
        if (record.getIntroduction() != null) {
            VALUES("introduction", "#{introduction,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_goods
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Goods record) {
        BEGIN();
        UPDATE("ps_goods");
        
        if (record.getTypeid() != null) {
            SET("typeid = #{typeid,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsname() != null) {
            SET("goodsname = #{goodsname,jdbcType=VARCHAR}");
        }
        
        if (record.getSize() != null) {
            SET("size = #{size,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsprice() != null) {
            SET("goodsprice = #{goodsprice,jdbcType=VARCHAR}");
        }
        
        if (record.getImages() != null) {
            SET("images = #{images,jdbcType=VARCHAR}");
        }
        
        if (record.getIntroduction() != null) {
            SET("introduction = #{introduction,jdbcType=VARCHAR}");
        }
        
        WHERE("goodsid = #{goodsid,jdbcType=INTEGER}");
        
        return SQL();
    }
}