package practical.wjc.dao;

import practical.wjc.entity.Orders;

import java.util.List;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_orders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_orders
     *
     * @mbggenerated
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_orders
     *
     * @mbggenerated
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_orders
     *
     * @mbggenerated
     */
    Orders selectByPrimaryKey(Integer orderid);
    List<Orders> selectByUserid(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Orders record);
    List<Orders> list();
}