package practical.wjc.dao;

import org.apache.ibatis.annotations.Param;
import practical.wjc.entity.Goods;
import practical.wjc.entity.Users;

import java.util.List;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_users
     *
     * @mbggenerated
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_users
     *
     * @mbggenerated
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_users
     *
     * @mbggenerated
     */
    Users selectByPrimaryKey(Integer userid);
    Users selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Users record);

    Users login(@Param("username")String username, @Param("password")String password);
    List<Users> list();
}