package practical.wjc.entity;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_admin.adminid
     *
     * @mbggenerated
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_admin.adminname
     *
     * @mbggenerated
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_admin.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_admin.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_admin.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_admin.adminid
     *
     * @return the value of ps_admin.adminid
     *
     * @mbggenerated
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_admin.adminid
     *
     * @param adminid the value for ps_admin.adminid
     *
     * @mbggenerated
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_admin.adminname
     *
     * @return the value of ps_admin.adminname
     *
     * @mbggenerated
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_admin.adminname
     *
     * @param adminname the value for ps_admin.adminname
     *
     * @mbggenerated
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_admin.password
     *
     * @return the value of ps_admin.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_admin.password
     *
     * @param password the value for ps_admin.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_admin.email
     *
     * @return the value of ps_admin.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_admin.email
     *
     * @param email the value for ps_admin.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_admin.telephone
     *
     * @return the value of ps_admin.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_admin.telephone
     *
     * @param telephone the value for ps_admin.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
}