package practical.wjc.entity;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_goods.goodsid
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_goods.typeid
     *
     * @mbggenerated
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_goods.goodsname
     *
     * @mbggenerated
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_goods.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_goods.goodsprice
     *
     * @mbggenerated
     */
    private String goodsprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_goods.images
     *
     * @mbggenerated
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_goods.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_goods.goodsid
     *
     * @return the value of ps_goods.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_goods.goodsid
     *
     * @param goodsid the value for ps_goods.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_goods.typeid
     *
     * @return the value of ps_goods.typeid
     *
     * @mbggenerated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_goods.typeid
     *
     * @param typeid the value for ps_goods.typeid
     *
     * @mbggenerated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_goods.goodsname
     *
     * @return the value of ps_goods.goodsname
     *
     * @mbggenerated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_goods.goodsname
     *
     * @param goodsname the value for ps_goods.goodsname
     *
     * @mbggenerated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_goods.size
     *
     * @return the value of ps_goods.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_goods.size
     *
     * @param size the value for ps_goods.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_goods.goodsprice
     *
     * @return the value of ps_goods.goodsprice
     *
     * @mbggenerated
     */
    public String getGoodsprice() {
        return goodsprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_goods.goodsprice
     *
     * @param goodsprice the value for ps_goods.goodsprice
     *
     * @mbggenerated
     */
    public void setGoodsprice(String goodsprice) {
        this.goodsprice = goodsprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_goods.images
     *
     * @return the value of ps_goods.images
     *
     * @mbggenerated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_goods.images
     *
     * @param images the value for ps_goods.images
     *
     * @mbggenerated
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_goods.introduction
     *
     * @return the value of ps_goods.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_goods.introduction
     *
     * @param introduction the value for ps_goods.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }
}