package practical.wjc.entity;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.orderid
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.goodstag
     *
     * @mbggenerated
     */
    private String goodstag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.quantity
     *
     * @mbggenerated
     */
    private String quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.buyer
     *
     * @mbggenerated
     */
    private String buyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.express
     *
     * @mbggenerated
     */
    private String express;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.orderdate
     *
     * @mbggenerated
     */
    private String orderdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_orders.total
     *
     * @mbggenerated
     */
    private Double total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.orderid
     *
     * @return the value of ps_orders.orderid
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.orderid
     *
     * @param orderid the value for ps_orders.orderid
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.userid
     *
     * @return the value of ps_orders.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.userid
     *
     * @param userid the value for ps_orders.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.goodstag
     *
     * @return the value of ps_orders.goodstag
     *
     * @mbggenerated
     */
    public String getGoodstag() {
        return goodstag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.goodstag
     *
     * @param goodstag the value for ps_orders.goodstag
     *
     * @mbggenerated
     */
    public void setGoodstag(String goodstag) {
        this.goodstag = goodstag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.quantity
     *
     * @return the value of ps_orders.quantity
     *
     * @mbggenerated
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.quantity
     *
     * @param quantity the value for ps_orders.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.buyer
     *
     * @return the value of ps_orders.buyer
     *
     * @mbggenerated
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.buyer
     *
     * @param buyer the value for ps_orders.buyer
     *
     * @mbggenerated
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.sex
     *
     * @return the value of ps_orders.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.sex
     *
     * @param sex the value for ps_orders.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.address
     *
     * @return the value of ps_orders.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.address
     *
     * @param address the value for ps_orders.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.telephone
     *
     * @return the value of ps_orders.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.telephone
     *
     * @param telephone the value for ps_orders.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.express
     *
     * @return the value of ps_orders.express
     *
     * @mbggenerated
     */
    public String getExpress() {
        return express;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.express
     *
     * @param express the value for ps_orders.express
     *
     * @mbggenerated
     */
    public void setExpress(String express) {
        this.express = express;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.orderdate
     *
     * @return the value of ps_orders.orderdate
     *
     * @mbggenerated
     */
    public String getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.orderdate
     *
     * @param orderdate the value for ps_orders.orderdate
     *
     * @mbggenerated
     */
    public void setOrderdate(String orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.state
     *
     * @return the value of ps_orders.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.state
     *
     * @param state the value for ps_orders.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_orders.total
     *
     * @return the value of ps_orders.total
     *
     * @mbggenerated
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_orders.total
     *
     * @param total the value for ps_orders.total
     *
     * @mbggenerated
     */
    public void setTotal(Double total) {
        this.total = total;
    }
}